---
- name: Task 6 - working with roles
  hosts: test
  become: true
  tasks:
    - name: Enable SELinux
      selinux:
        policy: targeted
        state: permissive

    - name: Pass variables to role
      import_role:
        name: roles/squatch-ssh
      vars:
        ssh_port: 2022
        AllowedUsers: joe
        PermitRootLogin: "no"
      when: ansible_os_family == 'RedHat'  
