# SPDX-License-Identifier: BSD-3-Clause
---
- hosts: node1
  vars:
    network_connections:

      # Create one ethernet profile and activate it.
      # The profile uses automatic IP addressing
      # and is tied to the interface by MAC address.
      - name: prod1
        state: up
        type: ethernet
        autoconnect: yes
        mac: 08:00:27:ec:7c:40
        mtu: 1450

  roles:
    - rhel-system-roles.network
