---
- name: Set up registry machine
  hosts: testreg
  become: true
  vars:
    registry_machine: node4.ansi.example.com
    insecure_reg: true
    images:
      - hello-world
      - mysql
      - mysql:5.7
  tasks:
    - name: Install podman
      yum:
        name: podman
        state: latest

    - name: Create image dir
      file:
        path: /var/lib/registry
        state: directory

    - block:
      - name: Set up INSECURE registries
        copy:
          content: |
            [registries.search]
            registries = ['{{ansible_fqdn}}:5000','registry.redhat.io', 'quay.io', 'docker.io']
            
            [registries.insecure]
            registries = ['{{ansible_fqdn}}:5000']
          dest: /etc/containers/registries.conf
      when: insecure_reg == true

    - name: Open FW
      firewalld:
        port: 5000/tcp
        state: enabled
        immediate: true
        permanent: true

    - name: Check for running registry container
      shell: podman ps | grep registry
      register: registry_running
      ignore_errors: true

    - name: Clean up any leftover registry containers
      shell: "podman container rm registry"
      when: registry_running.stdout != ''
      ignore_errors: true

    - name: Run registry container
      shell: "podman run -d --name registry -p 5000:5000 -v /var/lib/registry:/var/lib/registry registry:2"
      when: registry_running.stdout == ''

    - name: Pull images
      shell: "podman pull docker.io/library/{{ item }}"
      loop: "{{ images }}"

    - name: Tag images
      shell: "podman tag docker.io/library/{{ item }} node4.ansi.example.com:5000/{{ item }}"
      loop: "{{ images }}"

    - name: Push images
      shell: "podman push {{ registry_machine }}:5000/{{ item }}"
      loop: "{{ images }}"

