#!/bin/bash

ansible all -m user -a "name=andre groups=wheel append=true password={{ 'giant' | password_hash('sha512', 'mysecretsalt') }}" -k -K -b -u vagrant

ansible all -m authorized_key -a "user=andre state=present key={{ lookup('file', '/home/andre/.ssh/id_rsa.pub') }}" -k -K -b -u vagrant

ansible all -m copy -a "content='andre ALL=(ALL) NOPASSWD:ALL' dest=/etc/sudoers.d/andre" -k -K -b -u vagrant
