---
- name: Partitions
  hosts: 
    - node1.ansi.example.com
    - node2.ansi.example.com
  become: true
  tasks:
    - name: Is there a device /dev/sdb
      debug:
        msg: Device Does Not Exist
      when: ansible_devices['sdb'] is not defined
    - name: Create part
      block:
        - name: Create 1GB partition
          parted:
            device: /dev/sdb
            number: 1
            state: present
            part_end: 1GiB
      rescue:
        - name: Create 250MB partition
          parted:
            device: /dev/sdb
            number: 1
            state: present
            part_end: 250MiB
      when: ansible_devices['sdb'] is defined
