---
- name: try
  hosts: all
  become: true
  tasks:
    - name: Number 1
      block:
        - name: Copy Stuff
          copy:
            content: "TEST"
            dest: /home/fred/oyeah.txt
          failed_when: ansible_hostname == "node4"
      when: ansible_fqdn == 'node2.ansi.example.com'
      rescue:
        - name: Copy Rescue
          copy:
            content: "RESCUE"
            dest: /home/fred/oyeah.txt
