---
- name: Task 15 Ansible Facts
  hosts: database
  become: true
  tasks:
    - name: Create directory
      file:
        path: /etc/ansible/facts.d
        state: directory

    - name: Create custom fact
      copy:
        content: |
          [sample_exam]
          server_role=mysql
        dest: /etc/ansible/facts.d/custom.fact

    - name: reload facts
      setup:

    - name: Check for fact
      debug:
        msg: "Here it is: {{ ansible_local.custom.sample_exam }}"
