---
- name: Task 16 Software Packages
  hosts: all
  become: true
  tasks:
    - name: Install on proxy
      yum:
        name: "{{ item }}"
        state: latest
      loop: [mailx,tcpdump]
      when: ansible_hostname in groups['proxy']

    - name: Install on database
      yum:
        name: "{{ item }}"
        state: latest
      loop: [mailx,lsof]
      when: ansible_hostname in groups['database']
