---
- name: Task 7 Scheduled Tasks
  hosts: all
  become: true
  tasks:
    - name: Ensure a job that runs at 2 and 5 exists. Creates an entry like "0 5,2 * * ls -alh > /dev/null"
      cron:
        name: "Time Log"
        minute: "0"
        job: "date >> /var/log/time.log"
        user: root
     
