---
- name: Task 18 Templates
  hosts: all
  become: true
  tasks:
    - name: Create server list file
      template:
        src: server_list.j2
        dest: /etc/server_list.txt
        mode: "0604"
        setype: net_conf_t
      when: ansible_hostname in groups['database']
