---
- name: Task 6 Users and Groups
  hosts: all
  become: true
  vars_files:
    - vars/user_list.yml
    - secret.yml
  tasks:
    - name: Create some web users
      block:
        - name: Webserver users
          block:
            - name: Create user
              user:
                name: "{{ item.username }}"
                uid: "{{ item.uid }}"
                shell: /bin/bash
                password: "{{ user_password | password_hash('sha512','salt') }}"
              loop: "{{ users }}"
            - name: Upload ssh key
              authorized_key:
                user: "{{ item.username}}"
                state: present
                key: "{{ lookup('file','/home/automation/.ssh/id_rsa.pub')}}"
              loop: "{{ users }}"
              when: item.uid < 2000
      when: ansible_hostname in groups['webservers']

    - name: Create some db users
      block:
        - name: Database users
          block:
            - name: Create user
              user:
                name: "{{ item.username }}"
                uid: "{{ item.uid }}"
                shell: /bin/bash
                password: "{{ user_password | password_hash('sha512','salt') }}"
              loop: "{{ users }}"
            - name: Upload ssh key
              authorized_key:
                user: "{{ item.username}}"
                state: present
                key: "{{ lookup('file','/home/automation/.ssh/id_rsa.pub')}}"
              when: item.uid >= 2000
              loop: "{{ users }}"
      when: ansible_hostname in groups['database']
