---
# tasks file for sample-mysql
- name: Create a new primary partition with a size of 800MiB
  parted:
    device: /dev/sdb
    number: 1
    state: present
    flags: [ lvm ]
    part_end: 800MiB

- name: Create a volume group
  lvg:
    vg: vg_database
    pvs: /dev/sdb

- name: Create logical volume
  lvol:
    vg: vg_database
    lv: lv_mysql
    size: "512"

- name: Create mount point
  file:
    path: /mnt/mysql_backups
    state: directory
    
- name: Mount up logical volume
  mount:
    path: /mnt/mysql_backups
    src: /dev/mapper/vg_database/lv_mysql
    fstype: xfs
    state: present

- name: Install mariadb
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - mariadb 
    - mariadb-server
    - python3-PyMySQL

- name: Fire up services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - firewalld
    - mariadb

- name: Set up firewall rules
  firewalld:
    service: mysql
    state: enabled
    immediate: true
    permanent: true

- name: set root user password
  mysql_user:
    #login_user: root
    #login_password: devops
    name: root
    password: "{{ database_password }}"
    state: present

- name: Change the my.cnf file
  template:
    src: templates/my.cnf.j2
    dest: /etc/my.cnf
  notify: restart_mariadb
