---
- name: Task 15 - Work with Ansible Facts
  hosts: database
  become: true
  tasks:
    - name: Create facts directory
      file:
        path: /etc/ansible/facts.d
        state: directory
        recurse: true

    - name: Create custom.fact
      copy:
        content: |
          [sample_exam]
          server_role=mysql
        dest: /etc/ansible/facts.d/custom.fact

- name: Check for facts
  hosts: database
  become: true
  tasks:
    - name: Check var
      debug:
        msg: "{{ ansible_local.custom.sample_exam }}"
