---
- name: Task 3 - File Content
  hosts: proxy
  become: true
  tasks:
    - name: 
      copy:
        content: "Welcome to HAProxy server"
        dest: /etc/motd
        owner: root
        group: root
        mode: "0644"

- name: MOTD webserver play
  hosts: webservers 
  become: true
  tasks:
    - name: 
      copy:
        content: "Welcome to Apache server"
        dest: /etc/motd
        owner: root
        group: root
        mode: "0644"

- name: MOTD database play
  hosts: database
  become: true
  tasks:
    - name: 
      copy:
        content: "Welcome to MySQL server"
        dest: /etc/motd
        owner: root
        group: root
        mode: "0644"
