---
- name: Task 4 - SSH Server
  hosts: all
  become: true
  tasks:
    - name: Set motd banner
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: ^.*Banner
        line: Banner /etc/motd

    - name: Set X11Forwarding
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: .*X11Forwarding
        line: X11Forwarding no

    - name: Set MaxAuthTries
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: ^.*MaxAuthTries
        line: MaxAuthTries 3
       
    - name: Restart ssh
      service:
        name: sshd
        state: restarted
