---
- name: Task 8 Facts
  hosts: web
  become: true
  tasks:
    - name: Create Directory
      file:
        path: /etc/ansible/facts.d
        state: directory

    - name: Create fact file
      template:
        src: templates/custom.fact.j2
        dest: /etc/ansible/facts.d/custom.fact

    - name: Refresh Facts
      setup:

    - name: Test
      debug:
        msg: "{{ ansible_local['custom']['customer']['contact'] }}"
- name: Create dynamic index.html
  hosts: web
  become: true
  tasks:
    - name: Create index page
      template:
        src: templates/index.html.j2
        dest: /var/www/html/index.html

