---
- name: Task 4 Set up Repos
  hosts: all
  become: true
  tasks:
  
  - name: Add multiple repositories into the same file (1/2)
    yum_repository:
      name: base
      description: Exam BaseOS Repo
      file: exam
      baseurl: http://repo/BaseOS/
      gpgcheck: false
      enabled: true

  - name: Add multiple repositories into the same file (1/2)
    yum_repository:
      name: apps
      description: Exam AppStream Repo
      file: exam
      baseurl: http://repo/AppStream/
      gpgcheck: false
      enabled: true
