---
- name: Task 16 Scheduled
  hosts: all
  become: true
  tasks:
    - name: Ensure a job that runs every day at 5pm
      cron:
        name: "Dissmiss the staff"
        minute: "0"
        hour: "17"
        job: '/usr/bin/wall "Time to go home!"'
    
