---
# tasks file for sample-apache
- name: Install packages
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - httpd
    - mod_ssl
    - php
    - firewalld

- name: Apache running
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - httpd
    - firewalld

- name: Open firewall ports
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  loop:
    - http
    - https
    - ssh
    
- name: Create index file
  template:
    src: templates/index.html.j2
    dest: /var/www/html/index.html
  notify: restart_apache 
