#!/bin/bash

ansible all -m user -a 'name=automation state=present groups=wheel password="$6$U468BrpfGbLR7780$j4PWZzW1PXKJmGH29lju5ee3om8kjUvu6GHKHOMqjO48/qVJEOEZtYSwwMOElNYf4cs8grU6S0fC1ZkGkkSSR."' -b -k -K --user=vagrant

ansible all -m copy -a 'content="automation        ALL=(ALL)       NOPASSWD: ALL" dest=/etc/sudoers.d/automation owner=root group=root mode=0440' -b -k -K --user=vagrant

ansible all -m authorized_key -a "user=automation state=present key={{ lookup('file', '/home/automation/.ssh/id_rsa.pub') }}" -k

