---
- name: Task 14 - Use Archiving
  hosts: database
  become: true
  tasks:
    - name: Create directory
      file:
        path: /mnt/mysql_backups
        state: directory
        owner: root
        group: root
        mode: "0644"

    - name: Create file
      copy:
        content: dev,test,qa,prod
        dest: /mnt/mysql_backups/database_list.txt
        owner: root
        group: root
        mode: "0644"

    - name: Zip it up
      archive:
        path: /mnt/mysql_backups/database_list.txt
        dest: /mnt/mysql_backups/archive.gz
        format: gz

