---
- name: Task 12 - Security
  hosts: webservers
  become: true
  roles:
    - rhel-system-roles.selinux
  tasks:
    - name: http_can_connect
      seboolean:
        name: httpd_can_network_connect
        state: true
        persistent: true
