#!/bin/bash

ansible all -m user -a "name=fred groups=wheel append=true password={{ 'devops' | password_hash('sha512', 'mysalt') }}" -k -K -b -u vagrant

ansible all -m copy -a 'content="fred ALL=(ALL) NOPASSWD:ALL" dest=/etc/sudoers.d/fred' -k -K -b -u vagrant

ansible all -m authorized_key -a "user=fred state=present key={{ lookup('file', '/home/fred/.ssh/id_rsa.pub') }}" -k -K -b -u fred

