---
- name: Install packages
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ apache_pack }}"

- name: Run services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ apache_serv }}"

- name: Create index file
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

- name: FW Rules
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  loop: "{{ apache_rules }}"
