---
- name: Task 17 Ansible Galaxy Roles
  hosts: node1
  roles:
    - geerlingguy.nfs
  vars:
    nfs_exports:
      - /logical/backups *(ro,sync,no_root_squash)
  become: true
  tasks:
    - name: FW Rule
      firewalld:
        service: nfs
        state: enabled
        immediate: true
        permanent: true

  
- name: Play 2
  hosts: nyc_aws
  become: true
  tasks: 
    - name: Install nfs-utils
      yum:
        name: nfs-utils
        state: latest
    - name: Create mount point
      file:
        path: /configs
        state: directory
    - name: Mount the nfs share
      mount:
        path: /configs
        src: "node1:/logical/backups"
        fstype: nfs
        state: mounted

