---
- name: Task 10 RHEL System Roles
  hosts: node1
  become: true
  vars:
    timesync_ntp_servers:
      - hostname: time-a-g.nist.gov
        iburst: yes
      - hostname: time-a-wwwv.nist.gov
        iburst: yes
      - hostname: time-e-b.nist.gov
        iburst: yes
  roles:
    - rhel-system-roles.timesync

